version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: karyawan_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Afifsyamf21@
      POSTGRES_DB: karyawan_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: